0.1.0: Refactoring (#1)
* Upgrade Ktor to 1.5.2

* Refactoring

* Fix COPY

* Downgrade KMongo due to NoClassDefFoundError

* Fix serialization error

* Revert _id renaming

* Replace type-unsafe mongo java binding

* Replace write with File#writeBytes

* Update paths

* Fix POST data handling

* Set stella log definition

* Fix id reference

* Fix null type

* Revert to use GlobalScope

* Add HttpClient logging

* Implement REFRESH_TOKEN based Pixiv Auth

https://github.com/upbit/pixivpy/issues/158

* Refresh last token

* Refactoring

* Fix Nijie login